
var denamesForForm6 = new Array(
								
				"<font face='Arial' size=3><b>Ante Natal Care</b></font>",
				"<font face='Arial' size=2>Ante Natal cases Registered</font>",
				"<font face='Arial' size=2>a) Total</font>",
				"<font face='Arial' size=2>b) Less than 12 weeks</font>",
				"<font face='Arial' size=2>No. of pregnant women who had 3 check-ups</font>",
				"<font face='Arial' size=2>Total No. of high risk pregnant woman referred</font>",				
				"<font face='Arial' size=2>No. of TT doses</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TT1</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TT2</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Booster</font>",
				"<font face='Arial' size=2>No. of pregnant women under treatment for anaemia</font>",
				"<font face='Arial' size=2>No. of pregnant women given prophylaxis for anaemia</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>Natal Care<b></font>",
				"<font face='Arial' size=2>Total No. of deliveries</font>",
				"<font face='Arial' size=2>Home deliveries</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by ANM</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by LHV</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;by trained Birth Attendants</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Untrained Birth Attendants</font>",
				"<font face='Arial' size=2>Deliveries at sub-centre</font>",
				"<font face='Arial' size=2>Complicated delivieries referred to PHC / FRU</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>Pregnancy Outcome</b></font>",
				"&nbsp;",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Live births</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Still births</font>",
				"<font face='Arial' size=2>Order of Birth in 3.1 (a)</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1st</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2nd</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3rd</font>",
				"<font face='Arial' size=2>New born status at birth</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Less than 2.5 kg</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.5 kg or more</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of high risk new borns referred to PHC / FRU</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>Post Natal Care</b></font>",
				"<font face='Arial' size=2>No. of women given 3 post natal check-ups</font>",
				"<font face='Arial' size=2>Complications referred to PHC / FRU</font>",
				"<font face='Arial' size=3><b>Maternal Deaths</b></font>",
				"<font face='Arial' size=2>During pregnancy</font>",
				"<font face='Arial' size=2>During delivery</font>",
				"<font face='Arial' size=2>within 5 weeks of delivery</font>",		
				"&nbsp;",
				"<font face='Arial' size=3><b>RTI / STI</b></font>",
				"<font face='Arial' size=2>Cases</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Detected</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>Immunization</b></font>",
				"<font face='Arial' size=2>Infant 0 to 1 year</font>",
				"<font face='Arial' size=2>BCG</font>",
				"<font face='Arial' size=2>DPT1</font>",
				"<font face='Arial' size=2>DPT2</font>",
				"<font face='Arial' size=2>DPT3</font>",
				"<font face='Arial' size=2>OPV0</font>",
				"<font face='Arial' size=2>OPV1</font>",
				"<font face='Arial' size=2>OPV2</font>",
				"<font face='Arial' size=2>OPV3</font>",
				"<font face='Arial' size=2>Measles</font>",
				"<font face='Arial' size=2>Children more than 18 months</font>",
				"<font face='Arial' size=2>DPT Booster</font>",
				"<font face='Arial' size=2>OPV Booster</font>",
				"<font face='Arial' size=3><b>Full Immunization</b></font>",
				"<font face='Arial' size=2>Children more than 5 years</font>",
				"<font face='Arial' size=2>DT</font>",
				"<font face='Arial' size=2>Children more than 10 years</font>",
				"<font face='Arial' size=2>TT</font>",
				"<font face='Arial' size=2>Children more than 16 years</font>",
				"<font face='Arial' size=2>TT</font>",
				"<font face='Arial' size=3><b>Adverse Reactions reported after Immunization</b></font>",	
				"<font face='Arial' size=2>Vitamin A administration (9 months to 3 years)</font>",
				"<font face='Arial' size=2>Dose 1</font>",
				"<font face='Arial' size=2>Dose 2</font>",
				"<font face='Arial' size=2>Dose 3 - 5</font>",
				"<font face='Arial' size=3><b>Childhood Diseases</b></font>",
				"<font face='Arial' size=2>Vaccine preventable diseases</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Diptheria</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases Detected</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iv)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Poliomyelitis (AFP)</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases Detected</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iv)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",			
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Neo Natal Tetanus</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases Detected</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iv)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",
				"<font face='Arial' size=2>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Measles</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases Detected</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iii)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;iv)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",
				"<font face='Arial' size=2>ARI under 5 years (pneumonia)</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated with Co-trimoxozole</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred to PHC / FRU</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",
				"<font face='Arial' size=2>Acute Dianhoeal diseases under 5 years</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Treated with ORS</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Referred to PHC / FRU</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",

				"&nbsp;",
				"<font face='Arial' size=3><b>Child Deaths</b></font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with in 1 week</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1 week to 1 month</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1 month to 1 year</font>",
				"<font face='Arial' size=2>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1 year to 5 years</font>",

				"&nbsp;",			
				"<font face='Arial' size=3><b>Contraceptive Services</b></font>",		   
				"<font face='Arial' size=2>Eligible couples contacted</font>",
				"<font face='Arial' size=2>Male Sterilisation</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total no of cases motivated</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of cases followed up</font>",
				"<font face='Arial' size=2>Female Sterilisation</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Total no of cases motivated</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of cases followed up</font>",
				"<font face='Arial' size=2>Total IUD insertions</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases followed up</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Complications</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Discontinued</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Removed</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;Expelled</font>",
				"<font face='Arial' size=2>Total Oral Pill users</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Old Users</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New Users</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Complications</font>",
				"<font face='Arial' size=2>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Discontinued</font>",
				"<font face='Arial' size=2>Total condom users</font>",
				"<font face='Arial' size=3><b>Abortions</b></font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of women referred to MTP</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of MTP done</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cases followed up</font>",
				"<font face='Arial' size=2>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Complications</font>",
				"<font face='Arial' size=2>e)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deaths</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>Communicable Diseases</b></font>",
				"<font face='Arial' size=2>Malaria</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of fever identified</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of blood smear slides sent to PHC</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of fever cases given presumptive treatment</font>",
				"<font face='Arial' size=2>d)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of positive cases of malaria</font>",
				"<font face='Arial' size=2>e)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of positive cases given radical treatment</font>",
				"<font face='Arial' size=2>f)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of anti-mosquito activities co-ordinated</font>",
				"<font face='Arial' size=2>g)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of high risk villages identified</font>",
				"<font face='Arial' size=2>Tuberculosis</font>",
				"<font face='Arial' size=2>a)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of suspected cases</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;i)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Identified</font>",
				"<font face='Arial' size=2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ii)&nbsp;&nbsp;&nbsp;&nbsp;Referred</font>",
				"<font face='Arial' size=2>b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of sputum positive cases</font>",
				"<font face='Arial' size=2>c)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No. of TB cases followed up</font>",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;",
				"&nbsp;"
																										
				);



var slnoForForm6 = new Array(
								
				"<font face='Arial' size=3><b>1.</b></font>",
				"<font face='Arial' size=2>1.1</font>",
				" ",
				" ",
				"<font face='Arial' size=2>1.2</font>",
				"<font face='Arial' size=2>1.3</font>",
				"<font face='Arial' size=2>1.4</font>",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>1.5</font>",
				"<font face='Arial' size=2>1.6</font>",
				" ",
				"<font face='Arial' size=3><b>2.<b></font>",
				"<font face='Arial' size=2>2.1</font>",
				"<font face='Arial' size=2>2.2</font>",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>2.3</font>",
				"<font face='Arial' size=2>2.4</font>",
				"&nbsp;",
				"<font face='Arial' size=3><b>3.</b></font>",
				"<font face='Arial' size=2>3.1</font>",
				" ",
				" ",
				"<font face='Arial' size=2>3.2</font>",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>3.3</font>",
				" ",
				" ",
				" ",
				"&nbsp;",
				"<font face='Arial' size=3><b>4.</b></font>",
				"<font face='Arial' size=2>4.1</font>",
				"<font face='Arial' size=2>4.2</font>",
				"<font face='Arial' size=3><b>5.</b></font>",
				"<font face='Arial' size=2>5.1</font>",
				"<font face='Arial' size=2>5.2</font>",
				"<font face='Arial' size=2>5.3</font>",
				" ",
				"<font face='Arial' size=3><b>6.</b></font>",
				"<font face='Arial' size=2>6.1</font>",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=3><b>7.</b></font>",
				"<font face='Arial' size=2>7.1</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>7.2</font>",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>7.3</font>",
				" ",
				"<font face='Arial' size=2>7.4</font>",
				" ",
				"<font face='Arial' size=2>7.5</font>",
				" ",
				"<font face='Arial' size=3>7.6</font>",	
				"<font face='Arial' size=2>8.</font>",
				" ",
				" ",
				" ",
				"<font face='Arial' size=3><b>9.</b></font>",
				"<font face='Arial' size=2>9.1</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",				
				"<font face='Arial' size=2>9.2</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>9.3</font>",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>9.4</font>",
				" ",
				" ",
				" ",
				"&nbsp;",
				"<font face='Arial' size=3><b>10.</b></font>",
				" ",
				" ",
				" ",
				" ",			
				"&nbsp;",
				"<font face='Arial' size=3><b>11.</b></font>",		   
				"<font face='Arial' size=2>11.1</font>",
				"<font face='Arial' size=2>11.2</font>",
				" ",
				" ",
				"<font face='Arial' size=2>11.3</font>",
				" ",
				" ",
				"<font face='Arial' size=2>11.4</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>11.5</font>",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>11.6</font>",
				"<font face='Arial' size=3><b>12.</b></font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=3><b>13.</b></font>",
				"<font face='Arial' size=2>13.1</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				"<font face='Arial' size=2>13.2</font>",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" ",
				" "	
																									
				);
